export const Urls = {
loginUser:'/hrAdmin/user/loginUser',
checkLoginName:'/hrAdmin/user/checkLoginName',
getAllEmpInfoDetailsList:'/hrAdmin/getAllEmpInfoDetailsList',
searchByEmpInfoDetailsKeywords:'/hrAdmin/searchByEmpInfoDetailsKeywords',
importEmpInfoDetailsUrl:'/hrAdmin/importEmpInfoDetailsUrl',
importEmployeeDetailsUrl:'/hrAdmin/importEmployeeDetailsUrl',
saveEmpApplication:'hrAdmin/saveEmpApplication',
blockEmpInfo:'hrAdmin/blockEmpInfo',
unBlockEmpInfo:'hrAdmin/unBlockEmpInfo',
downloadEmpDetailsListExcel:'hrAdmin/downloadEmpDetailsListExcel',
exportEmpDetailsTemplate:'hrAdmin/exportEmpDetailsTemplate/template',
getListByEmpAppId:'hrAdmin/getListByEmpAppId',
exportEmpTemplate:'/hrAdmin/exportEmployeeDetailsUrl/template',
listEmployeeDetails:'/hrAdmin/getAllEmployeeList',
saveBonusScore:'hrAdmin/saveBonusScore',
searchByEmpBonusKeywords:'hrAdmin/searchByEmpBonusKeywords',
listEmpByBonusId:'hrAdmin/listEmpByBonusId',
getEmpListByBonusScore:'hrAdmin/getAllEmpBonusList',
importEmployeeBonusUrl:'hrAdmin/importEmployeeBonusUrl',
downloadEmpBonusList:'hrAdmin/downloadEmpBonusList',
getAllEmpBonusScoreList:'hrAdmin/getAllEmpBonusScoreList',
getAllTop6EmpBonusList:'hrAdmin/getAllTop6EmpBonusList',
exportEmpBonusTemplate:'/hrAdmin/exportEmpBonusTemplate/template',
searchByEmpKeywords:'/hrAdmin/searchByEmpKeywords',
exportEmpFundPlatformUrl:'/hrAdmin/exportEmpFundPlatformUrl/template',
importEmpFundDetailsUrl:'/hrAdmin/importEmpFundPlatformUrl',
listEmpFundPlatform:'/hrAdmin/getAllEmpFundPlatform',
searchByEmpFunPlatform:'/hrAdmin/searchByEmpFundPlatformKeywords',
downloadEmpListExcel:'hrAdmin/downloadEmpListExcel',
downloadEmpPlatformList:'hrAdmin/downloadEmpPlatformList',
uploadInvoiceUrl:'hrAdmin/uploadInvoiceUrl',
submitClaim:'hrAdmin/submitClaim',
updateClaim:'hrAdmin/updateClaim',
listClaim:'hrAdmin/listClaim',
getListByClaimId:'hrAdmin/getListByClaimId',
deleteClaim:'hrAdmin/deleteClaim',
saveAndSubmit:'hrAdmin/saveAndSubmit',
claimAppealTask:'hrAdmin/claimAppealTask',
claimRevoke:'hrAdmin/claimRevoke',
searchByClaimKeywords:'hrAdmin/searchByClaimKeywords',
claimTaskProcess:'hrAdmin/claimTaskProcess',
importActivityProcessDeploy:'hrAdmin/importActivityProcessDeploy',
listActivityDeploy:'hrAdmin/listActivityDeploy',
getClaimTaskList:'hrAdmin/getClaimTaskList',
getClaimTaskListByDeptApprove:'hrAdmin/getClaimTaskListByDeptApprove',
getClaimTaskListByFinanceApprove:'hrAdmin/getClaimTaskListByFinanceApprove',
completeApply:'hrAdmin/completeApply',
rejectApply:'hrAdmin/rejectApply',
taskTracking:'hrAdmin/taskTracking',
saveEmpFinalRanking:'hrAdmin/saveEmpFinalRanking',
empFinalRankingList:'hrAdmin/empFinalRankingList',
empFinalTotalRankingList:'hrAdmin/empFinalTotalRankingList',
saveEmpTotalFinal:'hrAdmin/saveEmpTotalFinal',
updateEmpTotalFinalRanking:'hrAdmin/updateEmpTotalFinalRanking',
empTotalFinalFindByDate:'hrAdmin/empTotalFinalFindByDate',
searchByEmpTotalFinalKeywords:'hrAdmin/searchByEmpTotalFinalKeywords',
downloadEmpFinalExcel:'hrAdmin/downloadEmpFinalExcel',
getEmpTotalFinalInfo:'hrAdmin/getEmpTotalFinalInfo',
exportEmpPointsHistoryTemplate:'hrAdmin/exportEmpPointsHistoryTemplate/template',
importEmpPointsHistoryUrl:'hrAdmin/importEmpPointsHistoryUrl',
getEmpListByPointsHis:'hrAdmin/getEmpListByPointsHis',
getEmpListByPointsDetailsHis:'hrAdmin/getEmpListByPointsDetailsHis',
searchByEmpHistoryKeywords:'hrAdmin/searchByEmpHistoryKeywords',
exportEmpGiftListTemplate:'hrAdmin/exportEmpGiftListTemplate/template',
importEmpGiftListUrl:'hrAdmin/importEmpGiftListUrl',
getAllEmpGiftList:'hrAdmin/getAllEmpGiftList',
findByEmpGiftId:'hrAdmin/findByEmpGiftId',
saveUserRegister:'hrAdmin/saveUserRegister',
searchByUserNameKeywords:'hrAdmin/searchByUserNameKeywords',
getUserInfo:'hrAdmin/getUserInfo',
saveRoleRegister:'hrAdmin/saveRoleRegister',
getRoleInfo:'hrAdmin/getRoleInfo',
getPersonalInfoById:'hrAdmin/getPersonalInfoById',
updatePersonalInfo:'hrAdmin/updatePersonalInfo',
updatePasswordById:'hrAdmin/updatePasswordById'

}
import { QueryEncoder } from "@angular/http";
export class CustomQueryEncoderHelper extends QueryEncoder {
    encodeKey(k: string): string {
        k = super.encodeKey(k);
        return k.replace(/\+/gi, '%2B');
    }
    encodeValue(v: string): string {
        v = super.encodeValue(v);
        return v.replace(/\+/gi, '%2B');
    }
}